export default function TermsPage() {
  return (
    <div className="py-16 sm:py-24">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold text-slate-50 mb-8">Terms of Service</h1>
        <div className="prose prose-invert prose-slate max-w-none space-y-6 text-slate-300 text-sm leading-relaxed">
          <p><strong>Effective Date:</strong> February 18, 2026</p>

          <h2 className="text-xl font-semibold text-slate-100 mt-8">1. Acceptance of Terms</h2>
          <p>
            By accessing or using GameFlow (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
            If you do not agree to these terms, do not use the Service.
          </p>

          <h2 className="text-xl font-semibold text-slate-100 mt-8">2. Description of Service</h2>
          <p>
            GameFlow provides AI-generated NBA player prop predictions, statistical analysis, and paper trading
            tools for informational and entertainment purposes. The Service does not constitute financial or
            gambling advice.
          </p>

          <h2 className="text-xl font-semibold text-slate-100 mt-8">3. No Guarantee of Results</h2>
          <p>
            Predictions and analyses are generated by machine learning models and are inherently uncertain.
            Past performance does not guarantee future results. You acknowledge that sports betting involves
            risk and that you are solely responsible for any wagers you place based on information from this Service.
          </p>

          <h2 className="text-xl font-semibold text-slate-100 mt-8">4. Pricing and Access</h2>
          <p>
            The Service is currently free during the beta period. We may introduce paid subscription
            plans in the future. Users will be notified in advance of any pricing changes.
          </p>

          <h2 className="text-xl font-semibold text-slate-100 mt-8">5. User Accounts</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials.
            You agree to provide accurate information and to notify us of any unauthorized use of your account.
          </p>

          <h2 className="text-xl font-semibold text-slate-100 mt-8">6. Prohibited Use</h2>
          <p>
            You may not resell, redistribute, or scrape data from the Service. Automated access without
            prior authorization is prohibited.
          </p>

          <h2 className="text-xl font-semibold text-slate-100 mt-8">7. Limitation of Liability</h2>
          <p>
            GameFlow is provided &quot;as is&quot; without warranties of any kind. In no event shall GameFlow
            be liable for any indirect, incidental, or consequential damages arising from your use of the Service.
          </p>

          <h2 className="text-xl font-semibold text-slate-100 mt-8">8. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the Service after
            changes constitutes acceptance of the updated terms.
          </p>

          <h2 className="text-xl font-semibold text-slate-100 mt-8">9. Contact</h2>
          <p>
            For questions about these terms, please contact us at support@gameflowdata.com.
          </p>
        </div>
      </div>
    </div>
  )
}
